# Generated by Django 5.2.6 on 2025-09-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('summary', models.TextField(blank=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='BZ Basel', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published', '-created_at'],
            },
        ),
    ]
